import "reflect-metadata";
import { container } from "tsyringe";
import { ProductRepository } from "../../modules/products/products.repository.js";
import { ProductService } from "../../modules/products/products.service.js";
import { ProductController } from "../../modules/products/products.controller.js";
import { ActivityLogRepository } from "../../modules/activity-logs/activity-logs.repository.js";
import { ActivityLogService } from "../../modules/activity-logs/activity-logs.service.js";
import { ActivityLogController } from "../../modules/activity-logs/activity-logs.controller.js";
import { InvoiceRepository } from "../../modules/invoices/invoices.repository.js";
import { InvoiceService } from "../../modules/invoices/invoices.service.js";
import { InvoiceController } from "../../modules/invoices/invoices.controller.js";
import { CustomerRepository } from "../../modules/customers/customers.repository.js";
import { CustomerService } from "../../modules/customers/customers.service.js";
import { DashboardRepository } from "../../modules/dashboard/dashboard.repository.js";
import { DashboardService } from "../../modules/dashboard/dashboard.service.js";
import { DashboardController } from "../../modules/dashboard/dashboard.controller.js";
import { CompanyRepository } from "../../modules/companies/company.repository.js";
import { CompanyService } from "../../modules/companies/company.service.js";
import { CompanyController } from "../../modules/companies/company.controller.js";
import { UserRepository, RefreshTokenRepository, VerificationTokenRepository } from "../../modules/auth/auth.repository.js";
import { AuthService } from "../../modules/auth/auth.service.js";
import { AuthController } from "../../modules/auth/auth.controller.js";
import { CustomerController } from "../../modules/customers/customers.controller.js";
import { PaymentRepository } from "../../modules/payments/payments.repository.js";
import { PaymentService } from "../../modules/payments/payments.service.js";
import { PaymentController } from "../../modules/payments/payments.controller.js";
import { ResendEmailService } from "../utils/email-resend.js";
import { StorageService } from "../storage/storage.service.js";
import type { ICacheService } from "../cache/cache.interface.js";
import { CacheService } from "../cache/cache.service.js";
import { redis } from "../../config/redis.js";

container.registerSingleton(ProductRepository);
container.registerSingleton(ActivityLogRepository);
container.registerSingleton(ActivityLogService);
container.registerSingleton(ProductService);
container.registerSingleton(ProductController);
container.registerSingleton(ActivityLogController);
container.registerSingleton(InvoiceRepository);
container.registerSingleton(InvoiceService);
container.registerSingleton(InvoiceController);
container.registerSingleton(CustomerRepository);
container.registerSingleton(CustomerService);
container.registerSingleton(DashboardRepository);
container.registerSingleton(DashboardService);
container.registerSingleton(DashboardController);
container.registerSingleton(CompanyRepository);
container.registerSingleton(CompanyService);
container.registerSingleton(CompanyController);
container.registerSingleton(UserRepository);
container.registerSingleton(RefreshTokenRepository);
container.registerSingleton(VerificationTokenRepository);
container.registerSingleton(ResendEmailService);
container.registerSingleton(AuthService);
container.registerSingleton(AuthController);
container.registerSingleton(CustomerController);
container.registerSingleton(StorageService);
container.registerSingleton(PaymentRepository);
container.registerSingleton(PaymentService);
container.registerSingleton(PaymentController);

container.registerInstance<ICacheService>(CacheService, new CacheService(redis));
